
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: postgres
  password: 1234
  database: jnecshopdb

test:
  <<: *default
  database: jnecshopdb

production:
  <<: *default
  database: jnecshop_production
  username: jnecshop
  password: <%= ENV['JNECSHOP_DATABASE_PASSWORD'] %>
